import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { run } from '../core/exec.mjs';
import { ensureDir } from '../core/util.mjs';
import { routedServices, entryServices } from '../config/load.mjs';
import { lanePorts, localUrl } from '../project/ports.mjs';
import { routerContainer, laneContainerName } from '../stack/compose.mjs';
import { containerHealth } from '../docker/containers.mjs';

// Router decision order for a request: lane entry port, then baggage header, then the Origin or
// Referer of a lane UI dev server, then the lane cookie. No match means the baseline.

const upVar = (svc) => `lanes_up_${svc.replace(/[^a-zA-Z0-9]/g, '_')}`;
const reEscape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function proxyCommon() {
  return `# generated by lanes - do not edit
proxy_http_version 1.1;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $lanes_conn_upgrade;
proxy_set_header baggage $lanes_baggage_out;
proxy_buffering off;
proxy_request_buffering off;
proxy_connect_timeout 5s;
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;
proxy_redirect off;
access_log /var/log/nginx/access.log lanes;
`;
}

function switchPage(p, title, body) {
  const links = Object.values(p.uis).map((u) => `<a href="${localUrl(u.port)}/">${u.label} (localhost:${u.port})</a>`).join(' &middot; ');
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title>`
    + '<style>body{font-family:system-ui,sans-serif;margin:3rem;max-width:40rem;line-height:1.5}code{background:#eee;padding:.1rem .3rem}</style>'
    + `</head><body><h1>${title}</h1>${body}${links ? `<p>${links}</p>` : ''}</body></html>`;
  return html.replace(/"/g, '\\"');
}

function responseHeaders(p, up) {
  return `    add_header ${p.routing.header} $lanes_lane always;\n    add_header ${p.routing.header}-Upstream $${up} always;\n`;
}

function serviceServer(p, svc) {
  const up = upVar(svc.name);
  const ck = p.routing.cookie;
  let s = `server {\n  listen ${svc.port};\n`;
  s += '  set $lanes_lane $lanes_from_baggage;\n';
  s += '  if ($lanes_lane = "") { set $lanes_lane $lanes_from_origin; }\n';
  s += '  if ($lanes_lane = "") { set $lanes_lane $lanes_from_referer; }\n';
  s += '  if ($lanes_lane = "") { set $lanes_lane $lanes_from_cookie; }\n';
  if (svc.entry) {
    s += '  location = /__lane/off {\n';
    s += `    add_header Set-Cookie "${ck}=; Path=/; Max-Age=0; SameSite=None; Secure" always;\n`;
    s += '    default_type text/html;\n';
    s += `    return 200 "${switchPage(p, 'Lane cookie cleared', '<p>This browser now uses the <b>baseline</b> for every service.</p>')}";\n  }\n`;
    s += '  location ~ ^/__lane/([a-z0-9-]+)$ {\n';
    s += `    add_header Set-Cookie "${ck}=$1; Path=/; Max-Age=2592000; SameSite=None; Secure" always;\n`;
    s += '    default_type text/html;\n';
    s += `    return 200 "${switchPage(p, 'Lane cookie set', '<p>This browser profile now routes to lane <b>$1</b> for every service that lane runs; everything else stays on the baseline.</p><p>Clear it with <code>/__lane/off</code>.</p>')}";\n  }\n`;
  }
  s += `  location / {\n    proxy_pass http://$${up};\n    include /etc/nginx/conf.d/proxy_common.inc;\n${responseHeaders(p, up)}  }\n}\n`;
  return s;
}

function entryServer(p, port, laneName, svc) {
  if (!laneName) {
    return `server {\n  listen ${port};\n  location / { default_type text/plain; return 503 "lanes: no lane is assigned to this entry port\\n"; }\n}\n`;
  }
  const up = upVar(svc.name);
  return `server {\n  listen ${port};\n  set $lanes_lane "${laneName}";\n`
    + `  location / {\n    proxy_pass http://$${up};\n    include /etc/nginx/conf.d/proxy_common.inc;\n${responseHeaders(p, up)}  }\n}\n`;
}

export function renderRouterConf(p, registry) {
  const active = Object.values(registry.lanes || {}).filter((l) => l.status !== 'stopped');
  const key = reEscape(p.routing.baggageKey);
  let conf = '# generated by lanes - do not edit (regenerated on every lanes up/down)\n';
  conf += 'resolver 127.0.0.11 valid=5s ipv6=off;\n';
  conf += 'client_max_body_size 0;\n';
  conf += "log_format lanes '$time_iso8601 :$server_port lane=$lanes_lane -> $proxy_host $status $request_method $request_uri ${request_time}s';\n";
  conf += "map $http_upgrade $lanes_conn_upgrade { default upgrade; '' close; }\n";
  conf += `map $http_baggage $lanes_from_baggage { default ""; "~*(?:^|[,;\\s])${key}=([a-z0-9-]+)" $1; }\n`;
  conf += `map $cookie_${p.routing.cookie.replace(/[^a-zA-Z0-9_]/g, '_')} $lanes_from_cookie { default ""; "~^([a-z0-9-]+)$" $1; }\n`;
  // A lane UI dev server puts its origin on every browser call, including code that hard-codes the
  // baseline port, so those calls stay in the lane without a cookie.
  let originMap = 'map $http_origin $lanes_from_origin {\n  default "";\n';
  let refererMap = 'map $http_referer $lanes_from_referer {\n  default "";\n';
  for (const lane of active) {
    for (const uiPort of Object.values(lanePorts(p, lane.number).ui)) {
      originMap += `  "~^https?://(localhost|127\\.0\\.0\\.1):${uiPort}$" "${lane.name}";\n`;
      refererMap += `  "~^https?://(localhost|127\\.0\\.0\\.1):${uiPort}(/|$)" "${lane.name}";\n`;
    }
  }
  conf += `${originMap}}\n${refererMap}}\n`;
  conf += `map $lanes_lane $lanes_baggage_out { "" $http_baggage; default "${p.routing.baggageKey}=$lanes_lane"; }\n\n`;

  const routed = routedServices(p);
  for (const svc of routed) {
    conf += `map $lanes_lane $${upVar(svc.name)} {\n  default "${svc.name}:${svc.port}";\n`;
    for (const lane of active) {
      if (lane.services.includes(svc.name)) conf += `  "${lane.name}" "${laneContainerName(lane.name, svc.name)}:${svc.port}";\n`;
    }
    conf += '}\n';
  }
  conf += '\n';
  for (const svc of routed) conf += serviceServer(p, svc);
  const byNumber = Object.fromEntries(active.map((l) => [l.number, l.name]));
  for (let n = 1; n <= p.lanes.max; n++) {
    const ports = lanePorts(p, n);
    for (const svc of entryServices(p)) conf += entryServer(p, ports.entry[svc.name], byNumber[n], svc);
  }
  conf += 'server {\n  listen 8099;\n  access_log off;\n  location = /__router/health { default_type text/plain; return 200 "ok\\n"; }\n}\n';
  return conf;
}

export function writeRouterConf(p, registry) {
  ensureDir(p.paths.routerDir);
  fs.writeFileSync(path.join(p.paths.routerDir, 'proxy_common.inc'), proxyCommon());
  fs.writeFileSync(path.join(p.paths.routerDir, 'lanes.conf'), renderRouterConf(p, registry));
}

export async function routerRunning(p) {
  return (await containerHealth(routerContainer(p))).status === 'running';
}

function confDigest(p) {
  const h = crypto.createHash('sha1');
  for (const f of ['proxy_common.inc', 'lanes.conf']) h.update(fs.readFileSync(path.join(p.paths.routerDir, f)));
  return h.digest('hex');
}

/**
 * Validates and hot-reloads the router. No-op when the baseline (and so the router) is down.
 * With onlyIfChanged, skips the reload when the config equals the last one loaded.
 */
export async function reloadRouter(p, { onlyIfChanged = false } = {}) {
  if (!(await routerRunning(p))) return { reloaded: false, reason: 'router not running' };
  const marker = path.join(p.paths.routerDir, '.loaded');
  const digest = confDigest(p);
  if (onlyIfChanged && fs.existsSync(marker) && fs.readFileSync(marker, 'utf8') === digest) return { reloaded: false, reason: 'unchanged' };
  const test = run('docker', ['exec', routerContainer(p), 'nginx', '-t'], { allowFail: true });
  if (!test.ok) throw new Error(`Generated router config is invalid:\n${test.stderr}`);
  run('docker', ['exec', routerContainer(p), 'nginx', '-s', 'reload']);
  fs.writeFileSync(marker, digest);
  return { reloaded: true };
}
